### ISSUE TITLE
About Distribution Loss

### ISSUE THREAD

**Issue by codyshen0000** [pkuxmq/Invertible-Image-Rescaling#20]
Hi, 
I have a doubt that has troubled me for a  while. Since the network is reversible, why do you use JS divergence instead of a series of Jacobians to constrain the distribution? (P.S. I also found  that you calculated Jacobian in your code, but did not use it)

**Comment by pkuxmq** [comment]
Hi, because our model transforms x to (y, z) and we don't know the explicit distribution of y (LR images). For normalizing flows, they transform x to z, where latent z follows the standard Gaussian distribution, i.e. p(z) is known, so they can compute p(x) based on p(z) and the Jacobian and use MLE to train the network. In our task, there is no explicit distribution on (y, z), so p(x) cannot be derived explicitly by Jacobian.

**Comment by codyshen0000** [comment]
got it! Thank u
