### ISSUE TITLE
why using gt size 144?

### ISSUE THREAD

**Issue by junhyoung-ew** [pkuxmq/Invertible-Image-Rescaling#47]
Hello, thanks you for researching!

I wonder why you use GT size 144?

LQ image size is 36, HQ image size is 144. that lost much information..

**Comment by pkuxmq** [comment]
For image super-resolution/rescaling tasks, it is the common practice to sample small patches for training efficiency, because original high-resolution images, e.g. 1080p, are too large for efficient neural network propagation and training (memory costs, training time, etc.). Low-level image tasks largely depend on relatively local features, so training with patches, e.g. GT size 144, can be effective and efficient, and then convolutional operations can also be generalized to larger resolutions for testing.
